apiVersion: v1
kind: PersistentVolume
metadata:
  name: common-storage
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: common-storage
  hostPath:
    path: /tmp

