---
version: "3.4"

# là on veut la configuration pour nextcloud 20
services: 
  app:
    image: nextcloud:20.0-apache
    environment:
      POSTGRES_DB: nextcloud_user
      POSTGRES_PASSWORD: nextcloud_pass
      POSTGRES_USER: nextcloud_user
      POSTGRES_HOST: db
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: admin
      # .nextcloud.svc.cluster.local
    volumes:
      - app_data:/var/www/html
    ports:
      - "8000:80"

  db:
    image: postgres:12.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: nextcloud_pass
      POSTGRES_USER: nextcloud_user
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  app_data:

